// secrets.h CONTAINS DEVICE CERTIFICATE INFO SET ON EACH DEVICE AT TIME OF "FACTORY" SETUP
// IT IS NOT USED, INCLUDED OR CALLED DURING NORMAL USE.

// ADD CERTIFICATE AND WIFI DETAILS IN LOCALLY NOT ON GITHUB

// NOTE TO FUTURE USERS: To repurpose the DL_Client for other uses outside of Domestic Light include "secrets.h" in the main sketch,
// then replace calls to prefs with calls to this secrets.file

// "FACTORY SETUP" USE NOTES
// Fill in the following info for the boards being flashed

// 1) AWS_IOT_ENDPOINT replacing the xxxx with the project AWS endpoint

// PER DEVICE CHANGE: 
// 2) THING_NAME (the DL UUID)
// 3) AWS_CERT_CRT (just the characters inside the certificate descript)
// 4) AWS_CERT_PRIVATE (just the characters inside the certificate descript)

// BE CERTAIN THAT THE CERTIFICATES MATCH THE THING_NAME / DL UUID AS THEY ARE KEYED TO THAT DEVICE.

// SEE README IN DL_client_INIT FOR MORE DETAILS on purpose of this "Factory setup" mode.

#include <pgmspace.h>

#define SECRET
#define THING_NAME "200038"     // 6 digit serial number CHANGE THIS FOR EACH BOARD. 

const char WIFI_SSID[] = "Fairview guest";                   // place to include the setup wifi network
const char WIFI_PASSWORD[] = "Fairviewguest!";           // this info will be erased by user at user setup 

const char AWS_IOT_ENDPOINT[] = "a1j7vs6yi09a0s-ats.iot.us-east-1.amazonaws.com";       //PROJECT AWS ENDPOINT. 
 
/// Amazon Root CA 1. DO NOT CHANGE. AWS FIXED ROOT CERTIFICATE.  
static const char AWS_CERT_CA[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF
ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6
b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL
MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv
b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj
ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM
9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw
IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6
VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L
93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm
jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA
A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI
U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs
N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv
o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU
5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy
rqXRfboQnoZsG4q5WTP468SQvvG5
-----END CERTIFICATE-----

)EOF";
 
// Device Certificate       
// CHANGE TO DEVICE SPECIFIC CERTIFICATE xxxx-certificate.pem.crt     CHANGE THIS PER SENSOR
static const char AWS_CERT_CRT[] PROGMEM = R"KEY(
-----BEGIN CERTIFICATE-----
MIIDWTCCAkGgAwIBAgIUfKm0wKYCJfeo6vkj5ItMYr0Rc/kwDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTIzMDcxMjA2NDA0
OFoXDTQ5MTIzMTIzNTk1OVowHjEcMBoGA1UEAwwTQVdTIElvVCBDZXJ0aWZpY2F0
ZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANkJpEJwO71P1x2u0lIZ
zVhUD0vWpzLYEXaI4gTFbLJfylVqzifDlbXz+yRdY1ypCA8oqG2CO8aZYN6t469Z
+Q3YQxNBnVj52PCwSRx8OiEhicEEuCjy+Z+bmzdrtkR1DSKoJdDpAr7K5rQmTviT
53gAjMUfXjf97ljFCoMsF09wJdedejIALHVjpe4jTe0sfTWbRWt7YRTeBegRmTFG
uiBOb7avg1D8x035VOsiWr0h7Zj2I/nRKoT9EcWXqmGDg9CTqxmcno3vw4uKQfZ9
GkecjZOD8O/B0XBrj00pP4+WWrAv5CU9Lgfk//mBT/7s7Smws4kAEhG4+uFl59FV
ORMCAwEAAaNgMF4wHwYDVR0jBBgwFoAURih9zNSNiJGFPRjrS0XRtHDgg3gwHQYD
VR0OBBYEFPvxrJFuqT0MzT71wqW4a/G/GaP1MAwGA1UdEwEB/wQCMAAwDgYDVR0P
AQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4IBAQCq/C35j7Ik9UHfUMSvQ4Cx6ROq
HzZMZkQQQyzhHmd+iJVq1GAv0oHJhXl6Bm9Op1DQ6NGexDPA9l7Wgfx25Mdg65tp
o6DG/fOHW/wFDNhlOWVdH4hluMhfJ0LSrY+4mt+sL45VkTFsz2vmm/npFdf5+k8j
cJk+eezp7sez1paxxocEGsVwFjawYYyQvwWFXW45OuedOjopfjayQaDQGEgOlUoR
auR9jWEky3f7CSxGuWQCbq1gtZG0AGJpX0rlOrdd8cM9D7kNJfHgGYohyRH7cRvV
Eyr9MBfKVLugz0mV1tYzmoCb3F/yzVKkKt7ZIV8RbvcpRe23d5xQwNk4b+/w
-----END CERTIFICATE-----


)KEY";
 
// Device Private Key         
//CHANGE TO THE DEVICE SPECIFIC PRIVATE KEY  xxxx.private.pem.key  CHANGE THIS PER SENSOR
static const char AWS_CERT_PRIVATE[] PROGMEM = R"KEY(
-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA2QmkQnA7vU/XHa7SUhnNWFQPS9anMtgRdojiBMVssl/KVWrO
J8OVtfP7JF1jXKkIDyiobYI7xplg3q3jr1n5DdhDE0GdWPnY8LBJHHw6ISGJwQS4
KPL5n5ubN2u2RHUNIqgl0OkCvsrmtCZO+JPneACMxR9eN/3uWMUKgywXT3Al1516
MgAsdWOl7iNN7Sx9NZtFa3thFN4F6BGZMUa6IE5vtq+DUPzHTflU6yJavSHtmPYj
+dEqhP0RxZeqYYOD0JOrGZyeje/Di4pB9n0aR5yNk4Pw78HRcGuPTSk/j5ZasC/k
JT0uB+T/+YFP/uztKbCziQASEbj64WXn0VU5EwIDAQABAoIBAQCxfi0TGG4CmDS4
Vawy8F76iWQpBVafQgyl/7O3ay1FgwkZactGwbDBqNIOH0GPGb05iGqVhBgWhoCu
G09ErDP9morgSJzBkzJTRBfGb+GqDp91dsKU2oBCgyMg47mfqoofeZvTiXtxRMX/
NgUHTQ3TGcAFxW1sJQKzHhFGzNwTXYXX+twBZS+lB9fFwOY+ltHaIvTkDdtOt/bI
pcb2c9FLeMQca7JAuko2m/sLvDQYcYtxP32Y7EfEc1N5SLmOaarAfZvktzSTJ/fO
X+iXfh38FRjib3biCWI2zq9Henxho+nEalAqQYXyD51H2NmqQ2JbX7t7rGewdunH
GBknV+KBAoGBAPdcFnae0lyAvfBArcKVW8vfdvbwz9VCYBhIAhHRWO8DP0UAhbCN
8IQB3L8HSn6o1VovVkxbmrpvv0mOpvPfTkcBai0YYEa7334JJnnfOrlK56ggjqON
NrjGQSmViu+5lx291JGZxaGQO/ZRa+swwCETLVPzaAF7npcflQhDCUiDAoGBAOCe
aVLOTlg/H+NaJ3pDyYG9NtzwAWRdpMhO+Pdy6CiLdmEBQCBPjNThR7Masyh2K7u7
WG4OUS7La6L5axd+ixgKBpCVccuSa1DsaOgsKtVU4n9ZblnamoN8Ipx7yhWLD/CA
nnBPH1rZ8+XV6JBoxmL5Iy48lIOea7td/2n/+MgxAoGBAKBs0QTNrJDhzk3rJMZ2
J7rpizZMp/4ftkMJMI5tv8gDyxztYcdHxx1WN9yM1fufc/+xg76yCn+vydfi9NRl
l1bly/7DOG2nmyMavCF+bY+OzP91Xg0koMDlk41st1cSfreDTkHAATTvXnQ6CkvW
qkTJMzSnQGT1z70jdnyNPZARAoGAIBAcwrg2ULx6Bc8ZsYc5nW5wBWuxFy2S1xEG
0vOxFhCKTmCKUdJpLP4XaQaXql/r8DlW7ybWCdL5w2LNGaZznnPX6g2bF88HyJ5m
fzXGy3r5depDKUpeIgS3QBUfjKG0HcWOWEPDGwnfmeBF+U8rendLwU7eeEdF45IQ
YoYqchECgYAY4gn1kMdK5ttjt7LgYVGN2i8efvp09hxs++iZI7IOzghJy9HFesu4
RQpu6OAmTMPmb8R4MxnML+qaA4U6Qz6ylBYxCoL0U3m2MSNBy0F1g/juEH19elJZ
hLj7/M/T1X23HbGTp5CEYiVPU4OkQY5IbDhVXnQSW8rrl5DyVEnoKA==
-----END RSA PRIVATE KEY-----


)KEY";